"""initial_schema

Revision ID: dae0025fdee3
Revises:
Create Date: 2026-10-02 18:10:37.434111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dae0025fdee3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("access_tier", sa.Integer(), nullable=False),
        sa.Column("allowed_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tos_notes", sa.Text(), nullable=True),
        sa.Column("rate_limit_per_second", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vertical", "domain", "country", name="uq_sources_vertical_domain_country"
        ),
    )
    op.create_index(op.f("ix_sources_country"), "sources", ["country"], unique=False)
    op.create_index(op.f("ix_sources_domain"), "sources", ["domain"], unique=False)
    op.create_index(op.f("ix_sources_vertical"), "sources", ["vertical"], unique=False)
    op.create_index("ix_sources_vertical_domain", "sources", ["vertical", "domain"], unique=False)
    op.create_table(
        "subjects",
        sa.Column("vertical", sa.String(length=50), nullable=False),
        sa.Column("normalized_key", sa.String(length=255), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vertical", "normalized_key", name="uq_subjects_vertical_normalized_key"
        ),
    )
    op.create_index(
        op.f("ix_subjects_normalized_key"), "subjects", ["normalized_key"], unique=False
    )
    op.create_index(op.f("ix_subjects_vertical"), "subjects", ["vertical"], unique=False)
    op.create_index(
        "ix_subjects_vertical_key", "subjects", ["vertical", "normalized_key"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("oauth_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_oauth_sub"), "users", ["oauth_sub"], unique=True)
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "offers",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("url_or_deeplink", sa.Text(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("fees", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("taxes", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("discounts", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("availability", sa.String(length=50), nullable=False),
        sa.Column("condition", sa.String(length=50), nullable=False),
        sa.Column("seller", sa.String(length=200), nullable=True),
        sa.Column("match_status", sa.String(length=50), nullable=False),
        sa.Column("matched_on", sa.String(length=50), nullable=True),
        sa.Column("match_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_status", sa.String(length=50), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "url_or_deeplink", name="uq_offers_source_canonical_url"),
    )
    op.create_index(op.f("ix_offers_source_id"), "offers", ["source_id"], unique=False)
    op.create_index(op.f("ix_offers_subject_id"), "offers", ["subject_id"], unique=False)
    op.create_index(
        "ix_offers_subject_status",
        "offers",
        ["subject_id", "match_status", "availability"],
        unique=False,
    )
    op.create_table(
        "product_details",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("variant", sa.String(length=200), nullable=True),
        sa.Column("gtin", sa.String(length=50), nullable=True),
        sa.Column("mpn", sa.String(length=100), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=2000), nullable=True),
        sa.Column("raw_specs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_details_brand"), "product_details", ["brand"], unique=False)
    op.create_index(op.f("ix_product_details_gtin"), "product_details", ["gtin"], unique=False)
    op.create_index(op.f("ix_product_details_mpn"), "product_details", ["mpn"], unique=False)
    op.create_index(
        op.f("ix_product_details_subject_id"), "product_details", ["subject_id"], unique=True
    )
    op.create_table(
        "trackers",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("check_interval_hours", sa.Integer(), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_currency", sa.String(length=3), nullable=True),
        sa.Column("price_drop_alert", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trackers_expires_at"), "trackers", ["expires_at"], unique=False)
    op.create_index(op.f("ix_trackers_locked_until"), "trackers", ["locked_until"], unique=False)
    op.create_index(op.f("ix_trackers_status"), "trackers", ["status"], unique=False)
    op.create_index(
        "ix_trackers_status_expires", "trackers", ["status", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_trackers_subject_id"), "trackers", ["subject_id"], unique=False)
    op.create_index(op.f("ix_trackers_user_id"), "trackers", ["user_id"], unique=False)
    op.create_index("ix_trackers_user_status", "trackers", ["user_id", "status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("deduplication_key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_deduplication_key"),
        "notifications",
        ["deduplication_key"],
        unique=True,
    )
    op.create_index(op.f("ix_notifications_offer_id"), "notifications", ["offer_id"], unique=False)
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_index(
        op.f("ix_notifications_tracker_id"), "notifications", ["tracker_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_table(
        "observations",
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("check_run_id", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("fees", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("taxes", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("availability", sa.String(length=50), nullable=False),
        sa.Column("price_status", sa.String(length=50), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offer_id", "check_run_id", name="uq_observations_offer_check_run"),
    )
    op.create_index(
        op.f("ix_observations_check_run_id"), "observations", ["check_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_observations_observed_at"), "observations", ["observed_at"], unique=False
    )
    op.create_index(op.f("ix_observations_offer_id"), "observations", ["offer_id"], unique=False)
    op.create_index(
        "ix_observations_offer_observed", "observations", ["offer_id", "observed_at"], unique=False
    )
    op.create_table(
        "tracked_offers",
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("is_original", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tracker_id"], ["trackers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracker_id", "offer_id", name="uq_tracked_offers_tracker_offer"),
    )
    op.create_index(
        op.f("ix_tracked_offers_offer_id"), "tracked_offers", ["offer_id"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_offers_tracker_id"), "tracked_offers", ["tracker_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_offers_tracker_id"), table_name="tracked_offers")
    op.drop_index(op.f("ix_tracked_offers_offer_id"), table_name="tracked_offers")
    op.drop_table("tracked_offers")
    op.drop_index("ix_observations_offer_observed", table_name="observations")
    op.drop_index(op.f("ix_observations_offer_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_observed_at"), table_name="observations")
    op.drop_index(op.f("ix_observations_check_run_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_tracker_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_offer_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_deduplication_key"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_trackers_user_status", table_name="trackers")
    op.drop_index(op.f("ix_trackers_user_id"), table_name="trackers")
    op.drop_index(op.f("ix_trackers_subject_id"), table_name="trackers")
    op.drop_index("ix_trackers_status_expires", table_name="trackers")
    op.drop_index(op.f("ix_trackers_status"), table_name="trackers")
    op.drop_index(op.f("ix_trackers_locked_until"), table_name="trackers")
    op.drop_index(op.f("ix_trackers_expires_at"), table_name="trackers")
    op.drop_table("trackers")
    op.drop_index(op.f("ix_product_details_subject_id"), table_name="product_details")
    op.drop_index(op.f("ix_product_details_mpn"), table_name="product_details")
    op.drop_index(op.f("ix_product_details_gtin"), table_name="product_details")
    op.drop_index(op.f("ix_product_details_brand"), table_name="product_details")
    op.drop_table("product_details")
    op.drop_index("ix_offers_subject_status", table_name="offers")
    op.drop_index(op.f("ix_offers_subject_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_source_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_users_oauth_sub"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_subjects_vertical_key", table_name="subjects")
    op.drop_index(op.f("ix_subjects_vertical"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_normalized_key"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_index("ix_sources_vertical_domain", table_name="sources")
    op.drop_index(op.f("ix_sources_vertical"), table_name="sources")
    op.drop_index(op.f("ix_sources_domain"), table_name="sources")
    op.drop_index(op.f("ix_sources_country"), table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
